# Generated by Django 3.2.12 on 2022-02-26 13:13

from django.db import migrations, models
import queue_app.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(db_index=True, default=queue_app.enums.TaskStatusEnum['IN_PROGRESS'])),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('execute_at', models.DateTimeField(null=True)),
                ('manually_scheduled', models.BooleanField(default=False)),
                ('number_of_retries', models.IntegerField(default=0)),
            ],
        ),
    ]
